### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by ibrokemypie** [ahyattdev/typetab#1]
Is a mac version possible?

**Comment by ahyattdev** [comment]
Unfortunately, not with the Safari extensions API

> The designated container area for Safari Extensions is the execution of normal HTML, CSS, and JavaScript within the Safari app, and the specific JavaScript APIs documented here and Safari Extensions Reference.

https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html

What would be needed is something like Substrate for mac. 

Something like that is in development (https://github.com/comex/substitute), but the development of it is going slowly. 

So it is "possible", but the tools to do it are just not there yet.

**Comment by ibrokemypie** [comment]
@ahyattdev What about with SIMBL, implemented like SafariStand has been? That seems to work well. in modifying some of Safari's default behaviours.

**Comment by ahyattdev** [comment]
https://github.com/norio-nomura/EasySIMBL

This updated version of SIMBL could be of use. It is a library that was previously unknown to me, so making a Mac OS X version could take time. It does look possible with this, however. 

Also, what version of Safari are you using? 9.1 has the functionality of TypeTab already. How is this needed?

**Comment by ibrokemypie** [comment]
Im running 9.1 and when opening a new tab that is set to anything but the default it does not select the address bar.

AFAIK EasySIMBL no longer works with El Capitan, although SIMBL 0.9.9 does, its what I'm currently running Safari Stand on.

https://github.com/w0lfschild/mySIMBL

**Comment by ahyattdev** [comment]
@ibrokemypie is using `⌘ + L` enough for how often you need to ender an address instead?
